edit install command

diff --git a/.github/workflows/pipeline.yml b/.github/workflows/pipeline.yml
--- a/.github/workflows/pipeline.yml
+++ b/.github/workflows/pipeline.yml
@@ -25,9 +25,9 @@ jobs:
           if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
 
       - name: Run tests
-      - uses: actions/checkout@v3
-        if: success() || failure()
-      - run: | 
+#      - uses: actions/checkout@v3
+#        if: success() || failure()
+        run: | 
 #          mkdir -p reports
           pytest -vs --browser=chrome-headless -n 3 --alluredir ./allure-results --clean-alluredir
 #          pytest -vs --browser=chrome-headless -n 3 --html=reports/report.html
