edit install command

diff --git a/.github/workflows/pipeline.yml b/.github/workflows/pipeline.yml
--- a/.github/workflows/pipeline.yml
+++ b/.github/workflows/pipeline.yml
@@ -1,3 +1,69 @@
+#name: Selenium Python with Allure Report
+#
+#on:
+#  push:
+#    branches:
+#      - master
+#  pull_request:
+#    branches:
+#      - master
+#
+#jobs:
+#  build:
+#    runs-on: ubuntu-latest
+#
+#    steps:
+#      - uses: actions/checkout@v3
+#      - uses: actions/setup-python@v3
+#        with:
+#          python-version: "3.10"
+#
+#      - name: Install dependencies
+#        run: |
+##          python -m pip install --upgrade pip
+##          pip install -r requirements.txt
+#          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
+#
+#      - name: Run tests
+##      - uses: actions/checkout@v3
+##        if: success() || failure()
+#        run: pytest -vs --browser=chrome-headless -n 3 --html=reports/report.html
+##          mkdir -p reports
+##          pytest -vs --browser=chrome-headless -n 3 --alluredir ./allure-results --clean-alluredir
+##          pytest -vs --browser=chrome-headless -n 3 --html=reports/report.html
+##      - name: Set output
+##        if: success() || failure()
+##        id: results
+##        run: echo "artifactPath=reports/" >> $GITHUB_OUTPUT
+#
+##      - uses: actions/upload-artifact@v3
+##        if: success() || failure()
+##        with:
+##          name: test-report
+##          path: ${{ steps.results.outputs.artifactPath }}
+#
+##      - name: Generate Allure HTML report
+##        run: allure generate allure-results
+#
+##      - name: Upload Allure HTML report
+##        uses: actions/upload-artifact@v3
+##        with:
+##          name: allure-report-html
+##          path: allure-results/index.html
+#
+##      - name: Upload Allure report
+##        uses: actions/upload-artifact@v3
+##        with:
+##          name: allure-report
+##          path: allure-results
+##
+##      - name: Send Results and Generate Allure Report
+##        uses: Xotabu4/send-to-allure-server-action@1
+##          # always() needed because we want report for failed tests as well
+##        if: ${{ always() }}
+##        with:
+##          allure-server-url: 'http://my-allure-server.com:5001/'
+
 name: Selenium Python with Allure Report
 
 on:
@@ -19,47 +85,13 @@ jobs:
           python-version: "3.10"
 
       - name: Install dependencies
-        run: |
-#          python -m pip install --upgrade pip
-#          pip install -r requirements.txt
-          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
+        run: pip install -r requirements.txt
 
       - name: Run tests
-#      - uses: actions/checkout@v3
-#        if: success() || failure()
-        run: pytest -vs --browser=chrome-headless -n 3 --html=reports/report.html
-#          mkdir -p reports
-#          pytest -vs --browser=chrome-headless -n 3 --alluredir ./allure-results --clean-alluredir
-#          pytest -vs --browser=chrome-headless -n 3 --html=reports/report.html
-#      - name: Set output
-#        if: success() || failure()
-#        id: results
-#        run: echo "artifactPath=reports/" >> $GITHUB_OUTPUT
+        run: pytest -vs --browser=chrome-headless -n 3 --alluredir ./allure-results --clean-alluredir
 
-#      - uses: actions/upload-artifact@v3
-#        if: success() || failure()
-#        with:
-#          name: test-report
-#          path: ${{ steps.results.outputs.artifactPath }}
-
-#      - name: Generate Allure HTML report
-#        run: allure generate allure-results
-
-#      - name: Upload Allure HTML report
-#        uses: actions/upload-artifact@v3
-#        with:
-#          name: allure-report-html
-#          path: allure-results/index.html
-
-#      - name: Upload Allure report
-#        uses: actions/upload-artifact@v3
-#        with:
-#          name: allure-report
-#          path: allure-results
-#
-#      - name: Send Results and Generate Allure Report
-#        uses: Xotabu4/send-to-allure-server-action@1
-#          # always() needed because we want report for failed tests as well
-#        if: ${{ always() }}
-#        with:
-#          allure-server-url: 'http://my-allure-server.com:5001/'
+      - name: Upload Allure report
+        uses: actions/upload-artifact@v3
+        with:
+          name: allure-report
+          path: allure-results
