add html report

diff --git a/.github/workflows/pipeline.yml b/.github/workflows/pipeline.yml
--- a/.github/workflows/pipeline.yml
+++ b/.github/workflows/pipeline.yml
@@ -24,7 +24,10 @@ jobs:
           pip install -r requirements.txt
 
       - name: Run tests
-        run: pytest -vs --browser=chrome-headless -n 3 --alluredir ./allure-results --clean-alluredir
+        run: | 
+          mkdir -p reports
+#          pytest -vs --browser=chrome-headless -n 3 --alluredir ./allure-results --clean-alluredir
+          pytest -vs --browser=chrome-headless -n 3 --html=reports/report.html
 #      - name: Generate Allure HTML report
 #        run: allure generate allure-results
 
@@ -33,15 +36,26 @@ jobs:
 #        with:
 #          name: allure-report-html
 #          path: allure-results/index.html
-      - name: Upload Allure report
-        uses: actions/upload-artifact@v3
-        with:
-          name: allure-report
-          path: allure-results
+      - name: Set output
+        if: success() || failure()
+        id: results
+        run: echo "artifactPath=reports/" >> $GITHUB_OUTPUT
 
-      - name: Send Results and Generate Allure Report
-        uses: Xotabu4/send-to-allure-server-action@1
-          # always() needed because we want report for failed tests as well
-        if: ${{ always() }}
+      - uses: actions/upload-artifact@v3
+        if: success() || failure()
         with:
-          allure-server-url: 'http://my-allure-server.com:5001/'
+          name: test-report
+          path: ${{ steps.results.outputs.artifactPath }}
+
+#      - name: Upload Allure report
+#        uses: actions/upload-artifact@v3
+#        with:
+#          name: allure-report
+#          path: allure-results
+#
+#      - name: Send Results and Generate Allure Report
+#        uses: Xotabu4/send-to-allure-server-action@1
+#          # always() needed because we want report for failed tests as well
+#        if: ${{ always() }}
+#        with:
+#          allure-server-url: 'http://my-allure-server.com:5001/'
